### ISSUE TITLE
Android Cordova not showing map.

### ISSUE THREAD

**Issue by Kestanous** [pauloborges/meteor-mapbox#3]
I can get the map to load on the web fine. Including on the default Chome app on an Android device. But when I run it as a native app on an Android it gives me a white screen with no map controls. I can get it to work on the iOS emulator and will be testing on an iPhone soon. I thought maybe it was a css issue but I can't see how:

html:
```html
<body> <!-- final result after iron:router, before MapBox init -->
<div id='mapDisplay'>
  <div class="mapper" id="map"></div>
</div>
</body>
```
css:
```css
div#mapDisplay {
  height: 100%;
  width: 100%;
 }
div.mapper {
  width: 100%;
  height: 100%;
}
```
